<a href="https://colab.research.google.com/github/KThrishul/Application-of-Python-Workshop/blob/master/Day_3_Ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DAY 3 EXERCISE PROGRAMS**

Write a Pandas program to create and display a one-dimensional array using series containing even numbers upto 10000


---


tip : use List Comprehension
ds = pd.Series([0,2, 4, 6, 8..... 10000])

In [ ]:
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64



Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type

In [ ]:
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64



Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.

---
Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]


In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


Write a Pandas program to convert a NumPy array to a Pandas series.

---

Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]

In [ ]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


Write a Pandas program to convert a given Series to an array.

---
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]


In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


Write a Pandas program to sort a given Series.

---

Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
a.sort()
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '300.12' '400' '400' '500' 'great' 'is' 'language'
 'python']


Write a Pandas program to create a subsets of a given series based on value and condition.

---
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]

---

value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5


In [ ]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [ ]:

import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


Write a Pandas program to get the elements of an array values into column-wise.

---

Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.

In [ ]:

import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])

First three rows of the data frame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


In [ ]:
import pandas as pd
xyz = pd.read_csv('titanic1.csv') 
print(xyz.head(1))

   PassengerId  Survived  Pclass  ...  Fare Cabin  Embarked
0            1         0       3  ...  7.25   NaN         S

[1 rows x 12 columns]


Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields #(titanic1.csv file).

In [ ]:
import pandas as pd
df = pd.read_csv('titanic1.csv')
seventh_movie = df.iloc[3]
print("Details of the seventh movie:")
print(seventh_movie)

Details of the seventh movie:
PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                      35
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object


Write a Pandas program to sort the DataFrame based on title_year from dataset of titanic1.csv for any particular three fields

In [ ]:
import pandas as pd
df = pd.read_csv('titanic1.csv')
result = df[['Survived', 'Name']]
print("Details of survived and names:")
print(result)

Details of survived and names:
     Survived                                               Name
0           0                            Braund, Mr. Owen Harris
1           1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2           1                             Heikkinen, Miss. Laina
3           1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4           0                           Allen, Mr. William Henry
..        ...                                                ...
886         0                              Montvila, Rev. Juozas
887         1                       Graham, Miss. Margaret Edith
888         0           Johnston, Miss. Catherine Helen "Carrie"
889         1                              Behr, Mr. Karl Howell
890         0                                Dooley, Mr. Patrick

[891 rows x 2 columns]


Write a Pandas program to sort the DataFrame based on country and language from dataset of titanic1.csv

In [ ]:
import pandas as pd
df = pd.read_csv('titanic1.csv')
# Create a smaller dataframe
small_df = df[['PassengerId', 'Survived', 'Name', 'Age', 'Cabin']]
result = small_df.sort_values('PassengerId')
print("DataFrame based on country and language.")
print(result)

DataFrame based on country and language.
     PassengerId  Survived  ...   Age  Cabin
0              1         0  ...  22.0    NaN
1              2         1  ...  38.0    C85
2              3         1  ...  26.0    NaN
3              4         1  ...  35.0   C123
4              5         0  ...  35.0    NaN
..           ...       ...  ...   ...    ...
886          887         0  ...  27.0    NaN
887          888         1  ...  19.0    B42
888          889         0  ...   NaN    NaN
889          890         1  ...  26.0   C148
890          891         0  ...  32.0    NaN

[891 rows x 5 columns]


Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable

In [ ]:
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x)

Original Array:
[[0.75856763 0.71467988 0.85991414 0.6122899 ]
 [0.8231971  0.962046   0.73403463 0.65270679]
 [0.59440257 0.0707301  0.66291731 0.00254789]
 [0.94024773 0.31221101 0.61654717 0.98743679]]


Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.23763478 0.23014857 0.79001242 0.03498531 0.9364185  0.9875809
  0.97538599 0.21959955 0.90624457 0.15519003]
 [0.06450978 0.02179318 0.07484979 0.1224092  0.35864248 0.0670093
  0.47162593 0.25779032 0.99616668 0.53912085]
 [0.69970374 0.34262471 0.02573466 0.83583062 0.07972377 0.30615882
  0.96059934 0.01800177 0.51337719 0.83596268]
 [0.6680427  0.26977353 0.33282475 0.72845872 0.51674863 0.18611706
  0.34096216 0.30732817 0.15021472 0.29724637]
 [0.47909939 0.9986381  0.68044763 0.37154639 0.79033177 0.09208604
  0.03507113 0.06896177 0.62714702 0.25262433]
 [0.89710554 0.62892071 0.10105319 0.44103331 0.1834567  0.91849004
  0.32446819 0.30029284 0.67466029 0.53740361]
 [0.31074236 0.70111399 0.28389138 0.4666996  0.02169589 0.0788565
  0.2590065  0.23515203 0.47548118 0.55069904]
 [0.61892506 0.12860726 0.95356296 0.47498696 0.94221074 0.43641378
  0.66572709 0.18985076 0.54589424 0.73140122]
 [0.38384814 0.21394889 0.6860881  0.54564849 0.80226672 0.19977869

Write a NumPy program to generate 8 random integers between 100 and 300

In [ ]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[127 233 259 150 210 117 194 134]


Write a NumPy program to create a random integer nos of size 20 and sort it.

In [ ]:
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.30108443 0.06699101 0.50671467 0.81441838 0.68056595 0.7510916
 0.54833767 0.93169216 0.30797189 0.41131017 0.79838684 0.45863111
 0.97187909 0.84901193 0.1184193  0.10209973 0.14180013 0.36249192
 0.60445071 0.08952533]
Sorted array:
[0.06699101 0.08952533 0.10209973 0.1184193  0.14180013 0.30108443
 0.30797189 0.36249192 0.41131017 0.45863111 0.50671467 0.54833767
 0.60445071 0.68056595 0.7510916  0.79838684 0.81441838 0.84901193
 0.93169216 0.97187909]
